--- # 端口 正式环境
#server:
#  port: 8443
#  ssl:
#    key-store: classpath:4183142_iazuresky.com.pfx
#    key-store-password: 90x06PJW
server:
    port: 8081
--- #数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.95.94:3306/simpleaccount?characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true&autoReconnect=true
    username: root
    password: zaq123
--- #mybatis配置
mybatis:
  mapper-locations:
  - classpath:com/simpleaccount/mapper/sqlmapper/*.xml
  type-aliases-package: com.simpleaccount.entry
  configuration:
    map-underscore-to-camel-case: true
--- #日志配置
logging:
    level:
      com.simpleaccount.mapper: DEBUG
      com.simpleaccount.controller: WARN
    config:
      classpath:logback-spring.xml
--- #redis缓存配置

spring:
  redis:
    host: 47.100.95.94
    port: 6479
    password: Ls892903912
logging.path:
  ./target/logs
weblogPath:
  ${logging.path}\\spring.log
#pagehelper分页插件配置
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
